package com.kadikular.quantimium.reactor;

import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.properties.IntegerProperty;

/**
 * The circuit traces on the Reactor's plinth. Each block has a value for each of its four edges: 0
 * for no trace, 1 or 2 for a trace crossing it in one of two lanes. The value is a hash of the
 * edge's own position in the world, so the blocks on either side of an edge always agree and the
 * traces run on from one block to the next, however the floor is laid. The art is generated by
 * tools/reactor_traces.py.
 */
public final class ReactorTraces {

    public static final IntegerProperty NORTH = IntegerProperty.create("trace_north", 0, 2);
    public static final IntegerProperty EAST = IntegerProperty.create("trace_east", 0, 2);
    public static final IntegerProperty SOUTH = IntegerProperty.create("trace_south", 0, 2);
    public static final IntegerProperty WEST = IntegerProperty.create("trace_west", 0, 2);

    private ReactorTraces() {}

    /** How many blocks a run of one column's or row's edges shares a value for. */
    static final int RUN = 6;
    /** Of every thousand runs, how many carry no trace. */
    static final int EMPTY_PER_THOUSAND = 650;
    /**
     * Of every thousand edges on a run that carries a trace, how many cross it in the other lane. A
     * block whose two edges differ draws its trace with a short diagonal jog between the lanes.
     */
    static final int FLIP_PER_THOUSAND = 200;

    /** {@code state} with the traces its position gives it. */
    public static BlockState at(BlockState state, BlockPos pos) {
        int x = pos.getX(), y = pos.getY(), z = pos.getZ();
        return state
                .setValue(NORTH, northSouth(x, y, z))
                .setValue(SOUTH, northSouth(x, y, z + 1))
                .setValue(WEST, westEast(x, y, z))
                .setValue(EAST, westEast(x + 1, y, z));
    }

    /**
     * The edge on the north side of the block at ({@code x}, {@code z}). Edges down one column share a
     * value for a run of {@link #RUN} blocks, staggered column by column, so a trace runs straight
     * through several blocks before it jogs, turns or ends. Matches tools/reactor_traces.py's preview.
     */
    static int northSouth(int x, int y, int z) {
        int offset = Integer.remainderUnsigned(hash(x, y, 11), RUN);
        return flip(pick(hash(x, y, Math.floorDiv(z + offset, RUN), 0)), hash(x, y, z, 2));
    }

    /** The edge on the west side of the block at ({@code x}, {@code z}), in runs along its row. */
    static int westEast(int x, int y, int z) {
        int offset = Integer.remainderUnsigned(hash(z, y, 13), RUN);
        return flip(pick(hash(z, y, Math.floorDiv(x + offset, RUN), 1)), hash(z, y, x, 3));
    }

    private static int pick(int hash) {
        int roll = Integer.remainderUnsigned(hash, 1000);
        if (roll < EMPTY_PER_THOUSAND) return 0;
        return roll < EMPTY_PER_THOUSAND + (1000 - EMPTY_PER_THOUSAND) / 2 ? 1 : 2;
    }

    /** The run's lane at this edge: now and then the other one, so the trace jogs across. */
    private static int flip(int lane, int hash) {
        if (lane == 0 || Integer.remainderUnsigned(hash, 1000) >= FLIP_PER_THOUSAND) return lane;
        return 3 - lane;
    }

    private static int hash(int... values) {
        int h = 0x9e3779b9;
        for (int value : values) {
            h = (h ^ value) * 0x85ebca6b;
            h ^= h >>> 13;
        }
        h *= 0xc2b2ae35;
        return h ^ (h >>> 16);
    }
}
